version: "3.9"

services:
  dynamodb-local:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"

#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     environment:
#       - AWS_REGION=us-west-2
#       - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
#     ports:
#       - "8080:8080"
#     depends_on:
#       - dynamodb-local
#     networks:
#       - my-network

networks:
  my-network:
    driver: bridge
