name: Deploy to AWS Lambda

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build binary
      run: |
        go get -u github.com/aws/aws-lambda-go/lambda
        GOOS=linux go build -o main main.go

    - name: Package and deploy
      uses: aws-actions/aws-deploy-lambda@v1
      with:
        region: us-east-1
        function-name:  ${{ secrets.AWS_FUNCTION_NAME }}
        package: main
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
